[{
  "history_id" : "p5ob71vf5jd",
  "history_input" : "from earth_data_utils import *\n\ndef search_ssh():\n  auth_earthaccess()\n  results = earthaccess.search_data(\n      short_name=ssh_short_name,\n      cloud_hosted=True,\n      temporal=(\"2021-07-01\", \"2021-09-30\"),\n  )\n  return results\n\ndef plot_subset(ds_subset):\n  ds_subset.plot(figsize=(12,6), x='Longitude', y='Latitude')\n  home_dir = os.path.expanduser('~')\n  \n  file_name = f\"geoweaver_plot_{str(uuid.uuid4())}.png\"\n  save_file_path = os.path.join(home_dir, file_name)\n  plt.savefig(save_file_path)\n  print(f\"new figure is saved to {save_file_path}\")\n\nwith get_dataset(search_ssh()) as ds:\n  subset = ds[\"SLA\"].sel(Latitude=slice(-79, 79), \n                       Longitude=slice(100,300)).std('Time')\n  plot_subset(subset)\n",
  "history_output" : "You're now authenticated with NASA Earthdata Login\nUsing token with expiration date: 08/19/2023\nUsing .netrc file for EDL\nGranules found: 18\n Opening 18 granules, approx size: 0.0 GB\nQUEUEING TASKS | :   0%|          | 0/18 [00:00<?, ?it/s]\nQUEUEING TASKS | : 100%|██████████| 18/18 [00:00<00:00, 2774.01it/s]\nPROCESSING TASKS | :   0%|          | 0/18 [00:00<?, ?it/s]\nPROCESSING TASKS | :   6%|▌         | 1/18 [00:00<00:12,  1.36it/s]\nPROCESSING TASKS | :  39%|███▉      | 7/18 [00:00<00:01, 10.50it/s]\nPROCESSING TASKS | :  56%|█████▌    | 10/18 [00:01<00:01,  7.91it/s]\nPROCESSING TASKS | :  72%|███████▏  | 13/18 [00:01<00:00, 10.25it/s]\nPROCESSING TASKS | :  83%|████████▎ | 15/18 [00:01<00:00, 10.93it/s]\nPROCESSING TASKS | :  94%|█████████▍| 17/18 [00:02<00:00,  8.38it/s]\nPROCESSING TASKS | : 100%|██████████| 18/18 [00:02<00:00,  8.45it/s]\nCOLLECTING RESULTS | :   0%|          | 0/18 [00:00<?, ?it/s]\nCOLLECTING RESULTS | : 100%|██████████| 18/18 [00:00<00:00, 108317.75it/s]\nnew figure is saved to /Users/joe/geoweaver_plot_5a4d5079-4856-482a-a544-5eed113df40c.png\n",
  "history_begin_time" : 1687321242315,
  "history_end_time" : 1687321309768,
  "history_notes" : null,
  "history_process" : "e57twj",
  "host_id" : "100001",
  "indicator" : "Done"
},{
  "history_id" : "OlEfyMoYiVxD",
  "history_input" : "from earth_data_utils import *\n\ndef search_ssh():\n  auth_earthaccess()\n  results = earthaccess.search_data(\n      short_name=ssh_short_name,\n      cloud_hosted=True,\n      temporal=(\"2021-07-01\", \"2021-09-30\"),\n  )\n  return results\n\ndef plot_subset(ds_subset):\n  ds_subset.plot(figsize=(12,6), x='Longitude', y='Latitude')\n  home_dir = os.path.expanduser('~')\n  \n  file_name = f\"geoweaver_plot_{str(uuid.uuid4())}.png\"\n  save_file_path = os.path.join(home_dir, file_name)\n  plt.savefig(save_file_path)\n  print(f\"new figure is saved to {save_file_path}\")\n\nwith get_dataset(search_ssh()) as ds:\n  subset = ds[\"SLA\"].sel(Latitude=slice(-79, 79), \n                       Longitude=slice(100,300)).std('Time')\n  plot_subset(subset)\n",
  "history_output" : "You're now authenticated with NASA Earthdata Login\nUsing token with expiration date: 08/19/2023\nUsing .netrc file for EDL\nGranules found: 18\n Opening 18 granules, approx size: 0.0 GB\nQUEUEING TASKS | :   0%|          | 0/18 [00:00<?, ?it/s]\nQUEUEING TASKS | : 100%|██████████| 18/18 [00:00<00:00, 5270.70it/s]\nPROCESSING TASKS | :   0%|          | 0/18 [00:00<?, ?it/s]\nPROCESSING TASKS | :   6%|▌         | 1/18 [00:00<00:14,  1.18it/s]\nPROCESSING TASKS | :  28%|██▊       | 5/18 [00:01<00:02,  5.96it/s]\nPROCESSING TASKS | :  39%|███▉      | 7/18 [00:01<00:02,  5.22it/s]\nPROCESSING TASKS | :  56%|█████▌    | 10/18 [00:01<00:01,  7.29it/s]\nPROCESSING TASKS | :  67%|██████▋   | 12/18 [00:01<00:00,  8.93it/s]\nPROCESSING TASKS | :  78%|███████▊  | 14/18 [00:02<00:00,  9.05it/s]\nPROCESSING TASKS | :  89%|████████▉ | 16/18 [00:02<00:00,  8.84it/s]\nPROCESSING TASKS | : 100%|██████████| 18/18 [00:02<00:00,  9.77it/s]\nPROCESSING TASKS | : 100%|██████████| 18/18 [00:02<00:00,  7.41it/s]\nCOLLECTING RESULTS | :   0%|          | 0/18 [00:00<?, ?it/s]\nCOLLECTING RESULTS | : 100%|██████████| 18/18 [00:00<00:00, 133387.76it/s]\nnew figure is saved to /Users/joe/geoweaver_plot_5341ed07-b674-48b2-b074-0d9589d0ecd5.png\n",
  "history_begin_time" : 1687321080423,
  "history_end_time" : 1687321146979,
  "history_notes" : null,
  "history_process" : "e57twj",
  "host_id" : null,
  "indicator" : "Done"
},{
  "history_id" : "xrg8cw77e4c",
  "history_input" : "from earth_data_utils import *\n\ndef search_ssh():\n  auth_earthaccess()\n  results = earthaccess.search_data(\n      short_name=ssh_short_name,\n      cloud_hosted=True,\n      temporal=(\"2021-07-01\", \"2021-09-30\"),\n  )\n  return results\n\ndef plot_subset(ds_subset):\n  ds_subset.plot(figsize=(12,6), x='Longitude', y='Latitude')\n  home_dir = os.path.expanduser('~')\n  \n  file_name = f\"geoweaver_plot_{str(uuid.uuid4())}.png\"\n  save_file_path = os.path.join(home_dir, file_name)\n  plt.savefig(save_file_path)\n  print(f\"new figure is saved to {save_file_path}\")\n\nds = get_dataset(search_ssh())\nsubset = ds[\"SLA\"].sel(Latitude=slice(-79, 79), \n                       Longitude=slice(100,300)).std('Time')\nplot_subset(subset)\n",
  "history_output" : "You're now authenticated with NASA Earthdata Login\nUsing token with expiration date: 08/19/2023\nUsing .netrc file for EDL\nGranules found: 18\n Opening 18 granules, approx size: 0.0 GB\nQUEUEING TASKS | :   0%|          | 0/18 [00:00<?, ?it/s]\nQUEUEING TASKS | : 100%|██████████| 18/18 [00:00<00:00, 3949.85it/s]\nPROCESSING TASKS | :   0%|          | 0/18 [00:00<?, ?it/s]\nPROCESSING TASKS | :   6%|▌         | 1/18 [00:00<00:14,  1.16it/s]\nPROCESSING TASKS | :  33%|███▎      | 6/18 [00:01<00:01,  7.37it/s]\nPROCESSING TASKS | :  44%|████▍     | 8/18 [00:01<00:01,  6.04it/s]\nPROCESSING TASKS | :  56%|█████▌    | 10/18 [00:01<00:01,  5.96it/s]\nPROCESSING TASKS | :  83%|████████▎ | 15/18 [00:02<00:00,  8.50it/s]\nPROCESSING TASKS | :  94%|█████████▍| 17/18 [00:02<00:00,  7.22it/s]\nPROCESSING TASKS | : 100%|██████████| 18/18 [00:02<00:00,  6.89it/s]\nCOLLECTING RESULTS | :   0%|          | 0/18 [00:00<?, ?it/s]\nCOLLECTING RESULTS | : 100%|██████████| 18/18 [00:00<00:00, 44912.24it/s]\nnew figure is saved to /Users/joe/geoweaver_plot_3f4ddef9-2021-4ec1-aa16-af8201ef8cec.png\nException ignored in: <function CachingFileManager.__del__ at 0x7fc5042bf1f0>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 244, in __del__\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 222, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function File.close at 0x7fc50491ad30>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function CachingFileManager.__del__ at 0x7fc5042bf1f0>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 244, in __del__\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 222, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function File.close at 0x7fc50491ad30>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function CachingFileManager.__del__ at 0x7fc5042bf1f0>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 244, in __del__\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 222, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function File.close at 0x7fc50491ad30>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function CachingFileManager.__del__ at 0x7fc5042bf1f0>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 244, in __del__\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 222, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function File.close at 0x7fc50491ad30>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function CachingFileManager.__del__ at 0x7fc5042bf1f0>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 244, in __del__\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 222, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function File.close at 0x7fc50491ad30>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function CachingFileManager.__del__ at 0x7fc5042bf1f0>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 244, in __del__\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 222, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function File.close at 0x7fc50491ad30>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function CachingFileManager.__del__ at 0x7fc5042bf1f0>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 244, in __del__\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 222, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function File.close at 0x7fc50491ad30>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function CachingFileManager.__del__ at 0x7fc5042bf1f0>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 244, in __del__\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 222, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function File.close at 0x7fc50491ad30>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function CachingFileManager.__del__ at 0x7fc5042bf1f0>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 244, in __del__\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 222, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function File.close at 0x7fc50491ad30>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function CachingFileManager.__del__ at 0x7fc5042bf1f0>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 244, in __del__\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 222, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function File.close at 0x7fc50491ad30>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function CachingFileManager.__del__ at 0x7fc5042bf1f0>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 244, in __del__\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 222, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function File.close at 0x7fc50491ad30>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function CachingFileManager.__del__ at 0x7fc5042bf1f0>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 244, in __del__\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 222, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function File.close at 0x7fc50491ad30>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function CachingFileManager.__del__ at 0x7fc5042bf1f0>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 244, in __del__\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 222, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function File.close at 0x7fc50491ad30>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function CachingFileManager.__del__ at 0x7fc5042bf1f0>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 244, in __del__\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 222, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function File.close at 0x7fc50491ad30>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function CachingFileManager.__del__ at 0x7fc5042bf1f0>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 244, in __del__\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 222, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function File.close at 0x7fc50491ad30>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function CachingFileManager.__del__ at 0x7fc5042bf1f0>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 244, in __del__\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 222, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function File.close at 0x7fc50491ad30>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function CachingFileManager.__del__ at 0x7fc5042bf1f0>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 244, in __del__\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 222, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function File.close at 0x7fc50491ad30>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function CachingFileManager.__del__ at 0x7fc5042bf1f0>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 244, in __del__\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 222, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function File.close at 0x7fc50491ad30>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\n",
  "history_begin_time" : 1687320459866,
  "history_end_time" : 1687320522986,
  "history_notes" : null,
  "history_process" : "e57twj",
  "host_id" : "100001",
  "indicator" : "Done"
},{
  "history_id" : "ldacdvjaxzg",
  "history_input" : "from earth_data_utils import *\n\ndef search_ssh():\n  auth_earthaccess()\n  results = earthaccess.search_data(\n      short_name=ssh_short_name,\n      cloud_hosted=True,\n      temporal=(\"2021-07-01\", \"2021-09-30\"),\n  )\n  return results\n\ndef plot_subset(ds_subset):\n  ds_subset.plot(figsize=(12,6), x='Longitude', y='Latitude')\n  home_dir = os.path.expanduser('~')\n  \n  file_name = f\"geoweaver_plot_{str(uuid.uuid4())}.png\"\n  save_file_path = os.path.join(home_dir, file_name)\n  plt.savefig(save_file_path)\n  print(f\"new figure is saved to {save_file_path}\")\n\nds = get_dataset(search_ssh())\nsubset = ds[\"SLA\"].sel(Latitude=slice(-79, 79), \n                       Longitude=slice(100,300))\n\t\t\t\t  .std('Time')\nplot_subset(subset)\n",
  "history_output" : "  File \"/Users/joe/gw-workspace/ldacdvjaxzg/retrieve_ssh.py\", line 24\n    .std('Time')\nIndentationError: unexpected indent\n",
  "history_begin_time" : 1687320442679,
  "history_end_time" : 1687320456151,
  "history_notes" : null,
  "history_process" : "e57twj",
  "host_id" : "100001",
  "indicator" : "Stopped"
},{
  "history_id" : "3J4LHk63scV7",
  "history_input" : "from earth_data_utils import *\n\ndef search_ssh():\n  auth_earthaccess()\n  results = earthaccess.search_data(\n      short_name=ssh_short_name,\n      cloud_hosted=True,\n      temporal=(\"2021-07-01\", \"2021-09-30\"),\n  )\n  return results\n\n\nplot_subset(get_subset(get_dataset(search_ssh()), \n                       \"SLA\", \n                       lat=slice(-79, 79), \n                       lon=slice(100,300)))\n",
  "history_output" : "You're now authenticated with NASA Earthdata Login\nUsing token with expiration date: 08/19/2023\nUsing .netrc file for EDL\nGranules found: 18\n Opening 18 granules, approx size: 0.0 GB\nQUEUEING TASKS | :   0%|          | 0/18 [00:00<?, ?it/s]\nQUEUEING TASKS | : 100%|██████████| 18/18 [00:00<00:00, 3880.02it/s]\nPROCESSING TASKS | :   0%|          | 0/18 [00:00<?, ?it/s]\nPROCESSING TASKS | :   6%|▌         | 1/18 [00:00<00:11,  1.43it/s]\nPROCESSING TASKS | :  22%|██▏       | 4/18 [00:00<00:02,  5.58it/s]\nPROCESSING TASKS | :  39%|███▉      | 7/18 [00:01<00:01,  8.84it/s]\nPROCESSING TASKS | :  50%|█████     | 9/18 [00:01<00:01,  7.71it/s]\nPROCESSING TASKS | :  67%|██████▋   | 12/18 [00:01<00:00, 10.65it/s]\nPROCESSING TASKS | :  78%|███████▊  | 14/18 [00:01<00:00, 10.72it/s]\nPROCESSING TASKS | :  89%|████████▉ | 16/18 [00:01<00:00, 10.95it/s]\nPROCESSING TASKS | : 100%|██████████| 18/18 [00:02<00:00, 10.14it/s]\nPROCESSING TASKS | : 100%|██████████| 18/18 [00:02<00:00,  8.62it/s]\nCOLLECTING RESULTS | :   0%|          | 0/18 [00:00<?, ?it/s]\nCOLLECTING RESULTS | : 100%|██████████| 18/18 [00:00<00:00, 134576.60it/s]\n<xarray.Dataset>\nDimensions:      (Time: 18, Longitude: 2160, nv: 2, Latitude: 960)\nCoordinates:\n  * Longitude    (Longitude) float32 0.08333 0.25 0.4167 ... 359.6 359.8 359.9\n  * Latitude     (Latitude) float32 -79.92 -79.75 -79.58 ... 79.58 79.75 79.92\n  * Time         (Time) datetime64[ns] 2021-07-05T12:00:00 ... 2021-09-28T12:...\nDimensions without coordinates: nv\nData variables:\n    Lon_bounds   (Time, Longitude, nv) float32 dask.array<chunksize=(1, 2160, 2), meta=np.ndarray>\n    Lat_bounds   (Time, Latitude, nv) float32 dask.array<chunksize=(1, 960, 2), meta=np.ndarray>\n    Time_bounds  (Time, nv) datetime64[ns] dask.array<chunksize=(1, 2), meta=np.ndarray>\n    SLA          (Time, Latitude, Longitude) float32 dask.array<chunksize=(1, 960, 2160), meta=np.ndarray>\n    SLA_ERR      (Time, Latitude, Longitude) float32 dask.array<chunksize=(1, 960, 2160), meta=np.ndarray>\nAttributes: (12/21)\n    Conventions:            CF-1.6\n    ncei_template_version:  NCEI_NetCDF_Grid_Template_v2.0\n    Institution:            Jet Propulsion Laboratory\n    geospatial_lat_min:     -79.916664\n    geospatial_lat_max:     79.916664\n    geospatial_lon_min:     0.083333336\n    ...                     ...\n    version_number:         2205\n    Data_Pnts_Each_Sat:     {\"16\": 743215, \"1007\": 674076}\n    source_version:         commit 58c7da13c0c0069ae940c33a82bf1544b7d991bf\n    SLA_Global_MEAN:        0.06428374482174487\n    SLA_Global_STD:         0.0905195660534004\n    latency:                final\nnew figure is saved to /Users/joe/geoweaver_plot_448c74de-c23d-4698-bcc2-8c7c3a877032.png\n",
  "history_begin_time" : 1687318567897,
  "history_end_time" : 1687318631048,
  "history_notes" : null,
  "history_process" : "e57twj",
  "host_id" : null,
  "indicator" : "Done"
},{
  "history_id" : "c48mssmk9eg",
  "history_input" : "from earth_data_utils import *\n\ndef search_ssh():\n  auth_earthaccess()\n  results = earthaccess.search_data(\n      short_name=ssh_short_name,\n      cloud_hosted=True,\n      temporal=(\"2021-07-01\", \"2021-09-30\"),\n  )\n  return results\n\n\nplot_subset(get_subset(get_dataset(search_ssh()), \n                       \"SLA\", \n                       lat=slice(-90, 90), \n                       lon=slice(-180,180)))\n",
  "history_output" : "You're now authenticated with NASA Earthdata Login\nUsing token with expiration date: 08/19/2023\nUsing .netrc file for EDL\nGranules found: 18\n Opening 18 granules, approx size: 0.0 GB\nQUEUEING TASKS | :   0%|          | 0/18 [00:00<?, ?it/s]\nQUEUEING TASKS | : 100%|██████████| 18/18 [00:00<00:00, 3965.62it/s]\nPROCESSING TASKS | :   0%|          | 0/18 [00:00<?, ?it/s]\nPROCESSING TASKS | :   6%|▌         | 1/18 [00:00<00:15,  1.07it/s]\nPROCESSING TASKS | :  22%|██▏       | 4/18 [00:01<00:02,  4.84it/s]\nPROCESSING TASKS | :  33%|███▎      | 6/18 [00:01<00:01,  6.53it/s]\nPROCESSING TASKS | :  44%|████▍     | 8/18 [00:01<00:01,  7.28it/s]\nPROCESSING TASKS | :  56%|█████▌    | 10/18 [00:01<00:01,  6.89it/s]\nPROCESSING TASKS | :  78%|███████▊  | 14/18 [00:01<00:00, 10.49it/s]\nPROCESSING TASKS | :  89%|████████▉ | 16/18 [00:02<00:00, 10.54it/s]\nPROCESSING TASKS | : 100%|██████████| 18/18 [00:02<00:00,  7.87it/s]\nPROCESSING TASKS | : 100%|██████████| 18/18 [00:02<00:00,  7.05it/s]\nCOLLECTING RESULTS | :   0%|          | 0/18 [00:00<?, ?it/s]\nCOLLECTING RESULTS | : 100%|██████████| 18/18 [00:00<00:00, 127745.30it/s]\n<xarray.Dataset>\nDimensions:      (Time: 18, Longitude: 2160, nv: 2, Latitude: 960)\nCoordinates:\n  * Longitude    (Longitude) float32 0.08333 0.25 0.4167 ... 359.6 359.8 359.9\n  * Latitude     (Latitude) float32 -79.92 -79.75 -79.58 ... 79.58 79.75 79.92\n  * Time         (Time) datetime64[ns] 2021-07-05T12:00:00 ... 2021-09-28T12:...\nDimensions without coordinates: nv\nData variables:\n    Lon_bounds   (Time, Longitude, nv) float32 dask.array<chunksize=(1, 2160, 2), meta=np.ndarray>\n    Lat_bounds   (Time, Latitude, nv) float32 dask.array<chunksize=(1, 960, 2), meta=np.ndarray>\n    Time_bounds  (Time, nv) datetime64[ns] dask.array<chunksize=(1, 2), meta=np.ndarray>\n    SLA          (Time, Latitude, Longitude) float32 dask.array<chunksize=(1, 960, 2160), meta=np.ndarray>\n    SLA_ERR      (Time, Latitude, Longitude) float32 dask.array<chunksize=(1, 960, 2160), meta=np.ndarray>\nAttributes: (12/21)\n    Conventions:            CF-1.6\n    ncei_template_version:  NCEI_NetCDF_Grid_Template_v2.0\n    Institution:            Jet Propulsion Laboratory\n    geospatial_lat_min:     -79.916664\n    geospatial_lat_max:     79.916664\n    geospatial_lon_min:     0.083333336\n    ...                     ...\n    version_number:         2205\n    Data_Pnts_Each_Sat:     {\"16\": 743215, \"1007\": 674076}\n    source_version:         commit 58c7da13c0c0069ae940c33a82bf1544b7d991bf\n    SLA_Global_MEAN:        0.06428374482174487\n    SLA_Global_STD:         0.0905195660534004\n    latency:                final\nnew figure is saved to /Users/joe/geoweaver_plot_28c83439-d770-4d3a-b252-ec4d66d2a6ee.png\n",
  "history_begin_time" : 1687318373828,
  "history_end_time" : 1687318438743,
  "history_notes" : null,
  "history_process" : "e57twj",
  "host_id" : "100001",
  "indicator" : "Done"
},{
  "history_id" : "7WWyuXGEBuVQ",
  "history_input" : "from earth_data_utils import *\n\ndef search_ssh():\n  auth_earthaccess()\n  results = earthaccess.search_data(\n      short_name=ssh_short_name,\n      cloud_hosted=True,\n      temporal=(\"2021-07-01\", \"2021-09-30\"),\n  )\n  return results\n\n\nplot_subset(get_subset(get_dataset(search_ssh()), \n                       \"SLA\", \n                       lat=slice(-90, 90), \n                       lon=slice(-180,180)))\n",
  "history_output" : "You're now authenticated with NASA Earthdata Login\nUsing token with expiration date: 08/19/2023\nUsing .netrc file for EDL\nGranules found: 18\n Opening 18 granules, approx size: 0.0 GB\nQUEUEING TASKS | :   0%|          | 0/18 [00:00<?, ?it/s]\nQUEUEING TASKS | : 100%|██████████| 18/18 [00:00<00:00, 4124.64it/s]\nPROCESSING TASKS | :   0%|          | 0/18 [00:00<?, ?it/s]\nPROCESSING TASKS | :   6%|▌         | 1/18 [00:00<00:14,  1.18it/s]\nPROCESSING TASKS | :  39%|███▉      | 7/18 [00:01<00:01,  8.69it/s]\nPROCESSING TASKS | :  56%|█████▌    | 10/18 [00:01<00:01,  7.09it/s]\nPROCESSING TASKS | :  67%|██████▋   | 12/18 [00:01<00:00,  7.87it/s]\nPROCESSING TASKS | :  78%|███████▊  | 14/18 [00:02<00:00,  7.55it/s]\nPROCESSING TASKS | :  94%|█████████▍| 17/18 [00:02<00:00, 10.00it/s]\nPROCESSING TASKS | : 100%|██████████| 18/18 [00:02<00:00,  7.80it/s]\nCOLLECTING RESULTS | :   0%|          | 0/18 [00:00<?, ?it/s]\nCOLLECTING RESULTS | : 100%|██████████| 18/18 [00:00<00:00, 93206.76it/s]\n<xarray.Dataset>\nDimensions:      (Time: 18, Longitude: 2160, nv: 2, Latitude: 960)\nCoordinates:\n  * Longitude    (Longitude) float32 0.08333 0.25 0.4167 ... 359.6 359.8 359.9\n  * Latitude     (Latitude) float32 -79.92 -79.75 -79.58 ... 79.58 79.75 79.92\n  * Time         (Time) datetime64[ns] 2021-07-05T12:00:00 ... 2021-09-28T12:...\nDimensions without coordinates: nv\nData variables:\n    Lon_bounds   (Time, Longitude, nv) float32 dask.array<chunksize=(1, 2160, 2), meta=np.ndarray>\n    Lat_bounds   (Time, Latitude, nv) float32 dask.array<chunksize=(1, 960, 2), meta=np.ndarray>\n    Time_bounds  (Time, nv) datetime64[ns] dask.array<chunksize=(1, 2), meta=np.ndarray>\n    SLA          (Time, Latitude, Longitude) float32 dask.array<chunksize=(1, 960, 2160), meta=np.ndarray>\n    SLA_ERR      (Time, Latitude, Longitude) float32 dask.array<chunksize=(1, 960, 2160), meta=np.ndarray>\nAttributes: (12/21)\n    Conventions:            CF-1.6\n    ncei_template_version:  NCEI_NetCDF_Grid_Template_v2.0\n    Institution:            Jet Propulsion Laboratory\n    geospatial_lat_min:     -79.916664\n    geospatial_lat_max:     79.916664\n    geospatial_lon_min:     0.083333336\n    ...                     ...\n    version_number:         2205\n    Data_Pnts_Each_Sat:     {\"16\": 743215, \"1007\": 674076}\n    source_version:         commit 58c7da13c0c0069ae940c33a82bf1544b7d991bf\n    SLA_Global_MEAN:        0.06428374482174487\n    SLA_Global_STD:         0.0905195660534004\n    latency:                final\nnew figure is saved to /Users/joe/geoweaver_plot_a6c910d8-e549-4047-b9c7-f439a95fb9ae.png\n",
  "history_begin_time" : 1687318144361,
  "history_end_time" : 1687318208276,
  "history_notes" : null,
  "history_process" : "e57twj",
  "host_id" : null,
  "indicator" : "Done"
},{
  "history_id" : "eGo2k6gHYjKS",
  "history_input" : "from earth_data_utils import *\n\ndef search_ssh():\n  auth_earthaccess()\n  results = earthaccess.search_data(\n      short_name=ssh_short_name,\n      cloud_hosted=True,\n      temporal=(\"2021-07-01\", \"2021-09-30\"),\n  )\n  return results\n\n\nplot_subset(get_subset(get_dataset(search_ssh()), \n                       \"SLA\", \n                       lat=slice(-90, 90), \n                       lon=slice(-180,180)))\n",
  "history_output" : "You're now authenticated with NASA Earthdata Login\nUsing token with expiration date: 08/19/2023\nUsing .netrc file for EDL\nGranules found: 18\n Opening 18 granules, approx size: 0.0 GB\nQUEUEING TASKS | :   0%|          | 0/18 [00:00<?, ?it/s]\nQUEUEING TASKS | : 100%|██████████| 18/18 [00:00<00:00, 3839.57it/s]\nPROCESSING TASKS | :   0%|          | 0/18 [00:00<?, ?it/s]\nPROCESSING TASKS | :   6%|▌         | 1/18 [00:00<00:13,  1.29it/s]\nPROCESSING TASKS | :  22%|██▏       | 4/18 [00:00<00:02,  5.60it/s]\nPROCESSING TASKS | :  33%|███▎      | 6/18 [00:01<00:01,  6.46it/s]\nPROCESSING TASKS | :  44%|████▍     | 8/18 [00:01<00:01,  7.82it/s]\nPROCESSING TASKS | :  56%|█████▌    | 10/18 [00:01<00:00,  8.13it/s]\nPROCESSING TASKS | :  67%|██████▋   | 12/18 [00:01<00:00,  8.81it/s]\nPROCESSING TASKS | :  78%|███████▊  | 14/18 [00:01<00:00, 10.17it/s]\nPROCESSING TASKS | :  89%|████████▉ | 16/18 [00:02<00:00, 10.47it/s]\nPROCESSING TASKS | : 100%|██████████| 18/18 [00:02<00:00,  9.22it/s]\nPROCESSING TASKS | : 100%|██████████| 18/18 [00:02<00:00,  7.77it/s]\nCOLLECTING RESULTS | :   0%|          | 0/18 [00:00<?, ?it/s]\nCOLLECTING RESULTS | : 100%|██████████| 18/18 [00:00<00:00, 125203.10it/s]\n<xarray.Dataset>\nDimensions:      (Time: 18, Longitude: 2160, nv: 2, Latitude: 960)\nCoordinates:\n  * Longitude    (Longitude) float32 0.08333 0.25 0.4167 ... 359.6 359.8 359.9\n  * Latitude     (Latitude) float32 -79.92 -79.75 -79.58 ... 79.58 79.75 79.92\n  * Time         (Time) datetime64[ns] 2021-07-05T12:00:00 ... 2021-09-28T12:...\nDimensions without coordinates: nv\nData variables:\n    Lon_bounds   (Time, Longitude, nv) float32 dask.array<chunksize=(1, 2160, 2), meta=np.ndarray>\n    Lat_bounds   (Time, Latitude, nv) float32 dask.array<chunksize=(1, 960, 2), meta=np.ndarray>\n    Time_bounds  (Time, nv) datetime64[ns] dask.array<chunksize=(1, 2), meta=np.ndarray>\n    SLA          (Time, Latitude, Longitude) float32 dask.array<chunksize=(1, 960, 2160), meta=np.ndarray>\n    SLA_ERR      (Time, Latitude, Longitude) float32 dask.array<chunksize=(1, 960, 2160), meta=np.ndarray>\nAttributes: (12/21)\n    Conventions:            CF-1.6\n    ncei_template_version:  NCEI_NetCDF_Grid_Template_v2.0\n    Institution:            Jet Propulsion Laboratory\n    geospatial_lat_min:     -79.916664\n    geospatial_lat_max:     79.916664\n    geospatial_lon_min:     0.083333336\n    ...                     ...\n    version_number:         2205\n    Data_Pnts_Each_Sat:     {\"16\": 743215, \"1007\": 674076}\n    source_version:         commit 58c7da13c0c0069ae940c33a82bf1544b7d991bf\n    SLA_Global_MEAN:        0.06428374482174487\n    SLA_Global_STD:         0.0905195660534004\n    latency:                final\nnew figure is saved to /Users/joe/geoweaver_plot_9089bce7-c48b-4890-baf6-39378f560160.png\n",
  "history_begin_time" : 1687318033950,
  "history_end_time" : 1687318098607,
  "history_notes" : null,
  "history_process" : "e57twj",
  "host_id" : null,
  "indicator" : "Done"
},{
  "history_id" : "mTInwsC39TCK",
  "history_input" : "from earth_data_utils import *\n\ndef search_ssh():\n  auth_earthaccess()\n  results = earthaccess.search_data(\n      short_name=ssh_short_name,\n      cloud_hosted=True,\n      temporal=(\"2021-07-01\", \"2021-09-30\"),\n  )\n  return results\n\n\nplot_subset(get_subset(get_dataset(search_ssh())))\n",
  "history_output" : "You're now authenticated with NASA Earthdata Login\nUsing token with expiration date: 08/19/2023\nUsing .netrc file for EDL\nGranules found: 18\n Opening 18 granules, approx size: 0.0 GB\nQUEUEING TASKS | :   0%|          | 0/18 [00:00<?, ?it/s]\nQUEUEING TASKS | : 100%|██████████| 18/18 [00:00<00:00, 4383.78it/s]\nPROCESSING TASKS | :   0%|          | 0/18 [00:00<?, ?it/s]\nPROCESSING TASKS | :   6%|▌         | 1/18 [00:00<00:14,  1.19it/s]\nPROCESSING TASKS | :  17%|█▋        | 3/18 [00:00<00:03,  3.76it/s]\nPROCESSING TASKS | :  28%|██▊       | 5/18 [00:01<00:02,  5.73it/s]\nPROCESSING TASKS | :  39%|███▉      | 7/18 [00:01<00:01,  7.84it/s]\nPROCESSING TASKS | :  50%|█████     | 9/18 [00:01<00:01,  8.02it/s]\nPROCESSING TASKS | :  61%|██████    | 11/18 [00:01<00:00,  7.53it/s]\nPROCESSING TASKS | :  72%|███████▏  | 13/18 [00:01<00:00,  8.93it/s]\nPROCESSING TASKS | :  89%|████████▉ | 16/18 [00:02<00:00, 10.71it/s]\nPROCESSING TASKS | : 100%|██████████| 18/18 [00:02<00:00, 11.39it/s]\nPROCESSING TASKS | : 100%|██████████| 18/18 [00:02<00:00,  7.82it/s]\nCOLLECTING RESULTS | :   0%|          | 0/18 [00:00<?, ?it/s]\nCOLLECTING RESULTS | : 100%|██████████| 18/18 [00:00<00:00, 63657.23it/s]\nnew figure is saved to /Users/joe/geoweaver_plot_a255c1ed-1dee-4a55-a07a-8115a9f33263.png\n",
  "history_begin_time" : 1687316997570,
  "history_end_time" : 1687317059966,
  "history_notes" : null,
  "history_process" : "e57twj",
  "host_id" : null,
  "indicator" : "Done"
},]
